import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Form from "../components/form";
import { Matrix } from "../components/boxs";
import Share from "../components/share";
import { motion, AnimatePresence } from "framer-motion";
import { useState } from "react";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	const [step, setStep] = useState(0);
	const [firstname, setFirstname] = useState("");
	const [lastname, setLastname] = useState("");
	const [email, setEmail] = useState("");
	const [phone, setPhone] = useState("");
	return (
		<>
			<Head>
				<title>Giveaway app</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<AnimatePresence>
					{step === 0 && (
						<Form
							setStep={setStep}
							firstname={firstname}
							setFirstname={setFirstname}
							lastname={lastname}
							setLastname={setLastname}
							email={email}
							setEmail={setEmail}
							phone={phone}
							setPhone={setPhone}
						/>
					)}
					{step === 1 && <Matrix setStep={setStep} />}
					{step === 2 && <Share setStep={setStep} />}
				</AnimatePresence>
			</main>
		</>
	);
}
